import { motion } from 'framer-motion'

export default function GeminiReport({ explanation, isSaaS = false }) {
  if (!explanation) return null

  // Split by newlines to render as points if they start with a bullet or number, or just paragraphs
  const lines = explanation.split('\n').filter(p => p.trim() !== '')

  if (isSaaS) {
    return (
      <div className="space-y-6">
        {lines.map((line, idx) => (
          <motion.div 
            key={idx}
            initial={{ opacity: 0, x: 10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: idx * 0.1 }}
            className="flex gap-3 group"
          >
            <div className="w-1.5 h-1.5 bg-white rounded-full mt-2 group-hover:scale-150 transition-all opacity-40 shrink-0" />
            <p className="text-sm font-bold text-white/90 leading-relaxed tracking-tight">
              {line.replace(/^[*•-]\s*/, '')}
            </p>
          </motion.div>
        ))}
        
        <div className="pt-6 mt-6 border-t border-white/5 flex items-center gap-2">
           <div className="w-2 h-2 rounded-sm bg-accent animate-pulse" />
           <p className="text-[10px] font-black text-white/40 uppercase tracking-widest">Inference Verified by LLama-3.3</p>
        </div>
      </div>
    )
  }

  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-white rounded-[2.5rem] border border-border-subtle shadow-sm overflow-hidden p-12 relative card-shadow"
    >
      <div className="absolute top-0 right-0 w-48 h-48 bg-primary/5 rounded-bl-full flex items-center justify-center -mr-12 -mt-12" />

      <div className="flex items-center gap-5 mb-10 relative">
        <div className="w-16 h-16 rounded-2xl bg-primary text-white flex items-center justify-center text-3xl font-black shadow-lg shadow-primary/20">
          ✨
        </div>
        <div>
          <h3 className="text-2xl font-black text-primary tracking-tight">AI Explainer Report</h3>
          <p className="text-xs text-text-muted font-bold uppercase tracking-widest mt-1">Generated by Groq Inference Node</p>
        </div>
      </div>

      <div className="space-y-6 text-base text-slate-700 leading-relaxed max-w-4xl font-medium relative">
        {lines.map((p, idx) => (
          <p key={idx}>{p}</p>
        ))}
      </div>

      <div className="mt-12 pt-8 border-t border-slate-50 flex items-center gap-3 text-[10px] font-black text-text-muted uppercase tracking-widest relative">
        <span className="flex items-center gap-1 italic"><div className="w-1 h-1 rounded-full bg-accent" /> Verified Fairness Engine Analysis</span>
        <span>·</span>
        <span>Certificate Registry: {Math.random().toString(36).substring(7).toUpperCase()}</span>
      </div>
    </motion.div>
  )
}
